disabled_rules: # rule identifiers to exclude from running
opt_in_rules: # some rules are only opt-in
included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
cyclomatic_complexity: 15
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 500
large_tuple:
  warning: 3
  error: 5
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 1000
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
function_body_length: 150
function_parameter_count:
  warning: 8
  error: 10
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 50
    error: 70
  excluded: iPhone # excluded via string
variable_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
